import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Header } from "../components/Widgets/headers";
import { ChatProvider } from "@/context/ChatContext";
import ChatIcon from "@/public/ChatIcon.png";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Travel Mate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link rel="icon" href={ChatIcon.src} />
          <link
            href="https://fonts.googleapis.com/css2?family=Anton&family=Changa:wght@200..800&family=Permanent+Marker&family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&family=Varela+Round&display=swap"
            rel="stylesheet"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="@/public/ChatIcon.png"
          />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased 
              bg-[#faf5ee] min-h-screen`}
        >
          <ChatProvider>
            <Header />
            {children}
          </ChatProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
